Description: Learn CD with CircleCI

Resources:
  InstanceSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from local only
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: aws-ec2-default
      SecurityGroupIds:
        - !Ref InstanceSecGroup
      ImageId: ami-0ba60995c1589da9d
