version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: aws cloudformation create-stack --stack-name udacity-cd --template-body file://servers.yml --region us-west-2

workflows:
  deploy_workflow:
    jobs:
      - create_infrastructure
