version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name servers
          when: on_fail

jobs:
  create_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ea:7d:21:ef:24:86:2a:4f:0b:b1:c3:fa:3f:e9:2a:4d"
      - run:
          name: Install Dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory main-apache-hello-world.yml

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install CURL
          command: apk add --update curl
      - run:
          name: Curl website
          command: |
            URL="https://blog.udacity.com/"
            if curl -s --head ${URL}
            then
              return 0
            else
              return 1
            fi

  destroy_stack:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Simulate Error
          command: |
            return 1
      - destroy_environment

  deploy_and_create_static_website:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy Static Website
          command: |
            aws cloudformation deploy \
            --template-file cloudfront/bucket.yml \
            --stack-name ${CIRCLE_WORKFLOW_ID:0:7} \
            --parameter-overrides NAME="${CIRCLE_WORKFLOW_ID:0:7}"

workflows:
  deploy_workflow:
    jobs:
      - deploy_and_create_static_website
