# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

default_docker: &default_docker
  docker:
    - image: circleci/node:13.8.0

commands:
  print_pipeline_id:
    description: A command to print Circle CI pipeline ID
    parameters:
      pipelineId:
        type: string
        default: $CIRCLE_WORKFLOW_ID
    steps:
      - run: echo << parameters.pipelineId >>

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

jobs:
  print_hello:
    <<: *default_docker
    environment:
      JOB_VAR: Hello
    steps:
      - run:
          name: Print Hello
          command: echo $JOB_VAR

  print_world:
    <<: *default_docker
    environment:
      JOB_VAR: World
    steps:
      - run:
          name: Print World
          command: echo $JOB_VAR

  print_workflow_id:
    <<: *default_docker
    steps:
      - print_pipeline_id

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world:
          requires: [print_hello]
      - print_workflow_id
